### ISSUE TITLE
name more descriptive component names 

### ISSUE THREAD

**Issue by Sara-Samer** [abdoafage/Udemy-React-Clone-2#2]
https://github.com/abdoafage/Udemy-React-Clone-2/blob/800808d4938710631bfc09ce1a011cf83fcb637c/src/component/SingleCoursePage/PageComponent.js#L14

**Comment by abdoafage** [comment]
I fixed this b0619cd5cd1500c28c8d0e461e524973061352cd

**Comment by Sara-Samer** [comment]
please do not close issues on your own accord. the new name `ContentOfPage` is still not descriptive
